### PR TITLE
Cgi integration updates

### PR DESCRIPTION
**Pull request by chris-giblin**
Added information on:

- key rotation
- mention removal of encryption headers from responses
- correct "no performance penalty"
- mention ApiVersions
- SASL implications
- coordinating proxy and broker with advertising property
- State AES-GCM for initial version

### CODE REVIEW

**Comment by scholzj** [comment]
@chris-giblin Does this replace the #19 PR?

**Comment by chris-giblin** [comment]
@scholzj yes. My intention was to commit to the #19. Sorry, I may have goofed updating  the PR and created a new one. Please let me know if you prefer that I update #19. Apologies!

**Comment by scholzj** [comment]
I can probably live with both ... @strimzi/maintainers WDYT?

**Comment by ppatierno** [comment]
@chris-giblin @scholzj I would stay with #19 and having the changes there. We already have discussions on that PR it would be bad losing those conversations which drove to changes and then having other discussions on this one.
@chris-giblin is it a big problem updating #19 with changes and closing this one? Thanks!

**Comment by chris-giblin** [comment]
@ppatierno Will do!

**Comment by chris-giblin** [comment]
Closing this PR. All discussion and changes are accessible in #19.

**Pull request closed without merging**
